import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';
import { EffectivePolicy } from '../types/rule';
import { RuleManager } from './ruleManager';

const GENERATED_HEADER = '<!-- Generated by Prompt by Prompt. Do not edit manually. -->';

type ProjectionScope = 'workspace' | 'global';
type ProjectionFormat = 'agents-md' | 'root-agents-md';
type ProjectionWriteMode = 'safe-overwrite' | 'overwrite';

interface PassiveRuleProjectionSettings {
  enabled: boolean;
  scope: ProjectionScope;
  outputPath: string;
  format: ProjectionFormat;
  writeMode: ProjectionWriteMode;
  includeEditorContext: boolean;
  includePreferences: boolean;
  includeTeamMetadata: boolean;
  autoRefresh: boolean;
}

export class RuleProjectionService {
  constructor(
    private readonly context: vscode.ExtensionContext,
    private readonly ruleManager: RuleManager
  ) {}

  public async rebuildProjectedRuleFile(options?: { silent?: boolean }): Promise<{ written: boolean; path?: string; reason?: string }> {
    const settings = this.getSettings();
    if (!settings.enabled) {
      return { written: false, reason: 'disabled' };
    }

    const targetPath = this.resolveOutputPath(settings);
    if (!targetPath) {
      if (!options?.silent) {
        vscode.window.showWarningMessage('No workspace is open for passive rule projection.');
      }
      return { written: false, reason: 'no-workspace' };
    }

    const policy = this.ruleManager.resolvePolicy();
    const rendered = this.renderProjectedRuleFile(policy, settings);
    await fs.promises.mkdir(path.dirname(targetPath), { recursive: true });

    if (settings.writeMode === 'safe-overwrite' && fs.existsSync(targetPath)) {
      const existing = await fs.promises.readFile(targetPath, 'utf8');
      if (!existing.startsWith(GENERATED_HEADER)) {
        throw new Error(`Refusing to overwrite non-generated rule file at ${targetPath}`);
      }
    }

    await fs.promises.writeFile(targetPath, rendered, 'utf8');
    return { written: true, path: targetPath };
  }

  public shouldAutoRefresh(): boolean {
    const settings = this.getSettings();
    return settings.enabled && settings.autoRefresh;
  }

  public getProjectedRuleFilePath(): string | undefined {
    const settings = this.getSettings();
    if (!settings.enabled) {
      return undefined;
    }

    return this.resolveOutputPath(settings);
  }

  private getSettings(): PassiveRuleProjectionSettings {
    const config = vscode.workspace.getConfiguration('pbp');
    return {
      enabled: config.get<boolean>('passiveRuleProjection.enabled', false),
      scope: config.get<ProjectionScope>('passiveRuleProjection.scope', 'workspace'),
      outputPath: config.get<string>('passiveRuleProjection.outputPath', '.pbp/compiled/AGENTS.md'),
      format: config.get<ProjectionFormat>('passiveRuleProjection.format', 'agents-md'),
      writeMode: config.get<ProjectionWriteMode>('passiveRuleProjection.writeMode', 'safe-overwrite'),
      includeEditorContext: config.get<boolean>('passiveRuleProjection.includeEditorContext', false),
      includePreferences: config.get<boolean>('passiveRuleProjection.includePreferences', true),
      includeTeamMetadata: config.get<boolean>('passiveRuleProjection.includeTeamMetadata', true),
      autoRefresh: config.get<boolean>('passiveRuleProjection.autoRefresh', true),
    };
  }

  private resolveOutputPath(settings: PassiveRuleProjectionSettings): string | undefined {
    if (path.isAbsolute(settings.outputPath)) {
      return settings.outputPath;
    }

    if (settings.scope === 'global') {
      return path.join(this.context.globalStorageUri.fsPath, settings.outputPath);
    }

    const workspaceRoot = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
    if (!workspaceRoot) {
      return undefined;
    }

    return path.join(workspaceRoot, settings.outputPath);
  }

  private renderProjectedRuleFile(policy: EffectivePolicy, settings: PassiveRuleProjectionSettings): string {
    switch (settings.format) {
      case 'root-agents-md':
        return this.renderRootAgentsMarkdown(policy, settings);
      case 'agents-md':
      default:
        return this.renderAgentsMarkdown(policy, settings);
    }
  }

  private renderAgentsMarkdown(policy: EffectivePolicy, settings: PassiveRuleProjectionSettings): string {
    const lines: string[] = [GENERATED_HEADER, '', '# Prompt by Prompt Project Policy'];

    if (settings.includeTeamMetadata) {
      if (policy.packId) {
        lines.push(`pack: ${policy.packId}`);
      }
      if (policy.profileId) {
        lines.push(`profile: ${policy.profileId}`);
      }
      if (policy.resolvedVersion || policy.declaredVersion) {
        lines.push(`resolvedVersion: ${policy.resolvedVersion ?? policy.declaredVersion}`);
      }
      lines.push('');
    }

    if (policy.guardrails.length > 0) {
      lines.push('## Guardrails');
      for (const guardrail of policy.guardrails) {
        lines.push(`- ${guardrail.text}`);
      }
      lines.push('');
    }

    if (settings.includePreferences && policy.preferences.length > 0) {
      lines.push('## Preferences');
      for (const preference of policy.preferences) {
        lines.push(`- ${preference.key}: ${preference.value}`);
      }
      lines.push('');
    }

    if (policy.rules.length > 0) {
      lines.push('## Active Rules');
      for (const rule of policy.rules) {
        lines.push(`### ${rule.title}`);
        const body = rule.body.trim();
        if (body) {
          lines.push(body);
        }
        lines.push('');
      }
    }

    return `${lines.join('\n').trim()}\n`;
  }

  private renderRootAgentsMarkdown(policy: EffectivePolicy, settings: PassiveRuleProjectionSettings): string {
    const lines: string[] = [GENERATED_HEADER, '', '# AGENTS'];

    if (settings.includeTeamMetadata) {
      lines.push('');
      lines.push('## Source');
      if (policy.packId) {
        lines.push(`- Pack: ${policy.packId}`);
      }
      if (policy.profileId) {
        lines.push(`- Profile: ${policy.profileId}`);
      }
      if (policy.resolvedVersion || policy.declaredVersion) {
        lines.push(`- Version: ${policy.resolvedVersion ?? policy.declaredVersion}`);
      }
    }

    if (policy.guardrails.length > 0) {
      lines.push('');
      lines.push('## Hard Rules');
      for (const guardrail of policy.guardrails) {
        lines.push(`- ${guardrail.text}`);
      }
    }

    if (settings.includePreferences && policy.preferences.length > 0) {
      lines.push('');
      lines.push('## Preferences');
      for (const preference of policy.preferences) {
        lines.push(`- ${preference.key}: ${preference.value}`);
      }
    }

    if (policy.rules.length > 0) {
      lines.push('');
      lines.push('## Working Rules');
      for (const rule of policy.rules) {
        lines.push('');
        lines.push(`### ${rule.title}`);
        if (rule.body.trim()) {
          lines.push(rule.body.trim());
        }
      }
    }

    return `${lines.join('\n').trim()}\n`;
  }
}
