import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const mockState = vi.hoisted(() => ({
  workspaceFolders: [] as Array<{ uri: { fsPath: string } }>,
  configValues: {} as Record<string, unknown>,
}));

vi.mock('vscode', async () => ({
  workspace: {
    get workspaceFolders() {
      return mockState.workspaceFolders;
    },
    getConfiguration: vi.fn(() => ({
      get: vi.fn((key: string, fallback?: unknown) => mockState.configValues[key.replace('pbp.', '')] ?? fallback),
    })),
  },
  window: {
    showWarningMessage: vi.fn(() => Promise.resolve(undefined)),
  },
}));

describe('RuleProjectionService', () => {
  let workspaceDir: string;
  let globalDir: string;

  beforeEach(async () => {
    workspaceDir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'pbp-projection-workspace-'));
    globalDir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'pbp-projection-global-'));
    mockState.workspaceFolders = [{ uri: { fsPath: workspaceDir } }];
    mockState.configValues = {
      'passiveRuleProjection.enabled': true,
      'passiveRuleProjection.scope': 'workspace',
      'passiveRuleProjection.outputPath': '.pbp/compiled/AGENTS.md',
      'passiveRuleProjection.format': 'agents-md',
      'passiveRuleProjection.writeMode': 'safe-overwrite',
      'passiveRuleProjection.includePreferences': true,
      'passiveRuleProjection.includeTeamMetadata': true,
      'passiveRuleProjection.autoRefresh': true,
    };
  });

  afterEach(async () => {
    await fs.promises.rm(workspaceDir, { recursive: true, force: true });
    await fs.promises.rm(globalDir, { recursive: true, force: true });
  });

  it('writes an agents-md projected rule file from effective policy', async () => {
    const { RuleProjectionService } = await import('../src/services/ruleProjectionService');
    const service = new RuleProjectionService(
      { globalStorageUri: { fsPath: globalDir } } as never,
      {
        resolvePolicy: vi.fn(() => ({
          packId: 'acme-engineering',
          profileId: 'frontend-standard',
          declaredVersion: '1.4.2',
          resolvedVersion: 'commit-sha',
          bindingSource: 'workspace',
          rules: [
            {
              id: 'r1',
              canonicalKey: 'team-pack:acme:coding-style',
              title: 'Coding Style',
              body: '- Prefer small, composable functions.',
              source: 'team-pack',
              priority: 400,
              required: false,
              kind: 'instruction',
              reason: 'Enabled by team policy profile',
            },
          ],
          preferences: [
            { key: 'packageManager', value: 'pnpm', sourceRuleId: 'r2' },
          ],
          guardrails: [
            { id: 'r3', text: 'Ensure terminal commands are compatible with the current shell.', severity: 'hard', sourceRuleId: 'r3' },
          ],
          notes: [],
          conflicts: [],
        })),
      } as never
    );

    const result = await service.rebuildProjectedRuleFile();
    expect(result.written).toBe(true);
    expect(result.path).toBe(path.join(workspaceDir, '.pbp', 'compiled', 'AGENTS.md'));

    const generated = await fs.promises.readFile(result.path!, 'utf8');
    expect(generated).toContain('Generated by Prompt by Prompt');
    expect(generated).toContain('pack: acme-engineering');
    expect(generated).toContain('## Guardrails');
    expect(generated).toContain('packageManager: pnpm');
    expect(generated).toContain('### Coding Style');
  });

  it('refuses safe overwrite when the target file was not generated by Prompt by Prompt', async () => {
    const targetPath = path.join(workspaceDir, '.pbp', 'compiled', 'AGENTS.md');
    await fs.promises.mkdir(path.dirname(targetPath), { recursive: true });
    await fs.promises.writeFile(targetPath, '# User managed file\n', 'utf8');

    const { RuleProjectionService } = await import('../src/services/ruleProjectionService');
    const service = new RuleProjectionService(
      { globalStorageUri: { fsPath: globalDir } } as never,
      {
        resolvePolicy: vi.fn(() => ({
          profileId: 'workspace-only',
          rules: [],
          preferences: [],
          guardrails: [],
          notes: [],
          conflicts: [],
        })),
      } as never
    );

    await expect(service.rebuildProjectedRuleFile()).rejects.toThrow('Refusing to overwrite non-generated rule file');
  });

  it('renders a root AGENTS style projection format', async () => {
    mockState.configValues['passiveRuleProjection.format'] = 'root-agents-md';
    mockState.configValues['passiveRuleProjection.outputPath'] = 'AGENTS.md';

    const { RuleProjectionService } = await import('../src/services/ruleProjectionService');
    const service = new RuleProjectionService(
      { globalStorageUri: { fsPath: globalDir } } as never,
      {
        resolvePolicy: vi.fn(() => ({
          packId: 'pbp-official-team-pack',
          profileId: 'default-development',
          declaredVersion: '1.0.0',
          resolvedVersion: '1.0.0',
          bindingSource: 'workspace',
          rules: [
            {
              id: 'r1',
              canonicalKey: 'team-pack:pbp-official-team-pack:coding-style',
              title: 'Coding Style',
              body: '- Prefer small, composable functions.',
              source: 'team-pack',
              priority: 400,
              required: false,
              kind: 'instruction',
              reason: 'Enabled by team profile',
            },
          ],
          preferences: [
            { key: 'packageManager', value: 'pnpm', sourceRuleId: 'r2' },
          ],
          guardrails: [
            { id: 'r3', text: 'Ensure terminal commands are compatible with the current shell.', severity: 'hard', sourceRuleId: 'r3' },
          ],
          notes: [],
          conflicts: [],
        })),
      } as never
    );

    const result = await service.rebuildProjectedRuleFile();
    const generated = await fs.promises.readFile(result.path!, 'utf8');
    expect(result.path).toBe(path.join(workspaceDir, 'AGENTS.md'));
    expect(generated).toContain('# AGENTS');
    expect(generated).toContain('## Hard Rules');
    expect(generated).toContain('## Working Rules');
    expect(generated).toContain('### Coding Style');
  });
});
