import * as fs from 'fs';
import * as path from 'path';
import { EffectivePolicy } from '../../types/rule';

const GENERATED_HEADER = '<!-- Generated by Prompt by Prompt. Do not edit manually. -->';

export interface ProjectorSettings {
  format: 'agents-md' | 'root-agents-md';
  writeMode: 'safe-overwrite' | 'overwrite';
  includePreferences: boolean;
  includeTeamMetadata: boolean;
}

export class RuleProjector {
  async writeProjectedFile(targetPath: string, policy: EffectivePolicy, settings: ProjectorSettings): Promise<void> {
    const rendered = this.render(policy, settings);
    await fs.promises.mkdir(path.dirname(targetPath), { recursive: true });

    if (settings.writeMode === 'safe-overwrite' && fs.existsSync(targetPath)) {
      const existing = await fs.promises.readFile(targetPath, 'utf8');
      if (!existing.startsWith(GENERATED_HEADER)) {
        throw new Error(`Refusing to overwrite non-generated file at ${targetPath}`);
      }
    }

    await fs.promises.writeFile(targetPath, rendered, 'utf8');
  }

  render(policy: EffectivePolicy, settings: ProjectorSettings): string {
    return settings.format === 'root-agents-md'
      ? this.renderRootAgents(policy, settings)
      : this.renderAgentsMd(policy, settings);
  }

  private renderAgentsMd(policy: EffectivePolicy, settings: ProjectorSettings): string {
    const lines: string[] = [GENERATED_HEADER, '', '# Prompt by Prompt Project Policy'];

    if (settings.includeTeamMetadata) {
      if (policy.packId) lines.push(`pack: ${policy.packId}`);
      if (policy.profileId) lines.push(`profile: ${policy.profileId}`);
      if (policy.resolvedVersion ?? policy.declaredVersion) {
        lines.push(`resolvedVersion: ${policy.resolvedVersion ?? policy.declaredVersion}`);
      }
      lines.push('');
    }

    if (policy.guardrails.length > 0) {
      lines.push('## Guardrails');
      for (const g of policy.guardrails) lines.push(`- ${g.text}`);
      lines.push('');
    }

    if (settings.includePreferences && policy.preferences.length > 0) {
      lines.push('## Preferences');
      for (const p of policy.preferences) lines.push(`- ${p.key}: ${p.value}`);
      lines.push('');
    }

    if (policy.rules.length > 0) {
      lines.push('## Active Rules');
      for (const rule of policy.rules) {
        lines.push(`### ${rule.title}`);
        if (rule.body.trim()) lines.push(rule.body.trim());
        lines.push('');
      }
    }

    return `${lines.join('\n').trim()}\n`;
  }

  private renderRootAgents(policy: EffectivePolicy, settings: ProjectorSettings): string {
    const lines: string[] = [GENERATED_HEADER, '', '# AGENTS'];

    if (settings.includeTeamMetadata) {
      lines.push('', '## Source');
      if (policy.packId) lines.push(`- Pack: ${policy.packId}`);
      if (policy.profileId) lines.push(`- Profile: ${policy.profileId}`);
      if (policy.resolvedVersion ?? policy.declaredVersion) {
        lines.push(`- Version: ${policy.resolvedVersion ?? policy.declaredVersion}`);
      }
    }

    if (policy.guardrails.length > 0) {
      lines.push('', '## Hard Rules');
      for (const g of policy.guardrails) lines.push(`- ${g.text}`);
    }

    if (settings.includePreferences && policy.preferences.length > 0) {
      lines.push('', '## Preferences');
      for (const p of policy.preferences) lines.push(`- ${p.key}: ${p.value}`);
    }

    if (policy.rules.length > 0) {
      lines.push('', '## Working Rules');
      for (const rule of policy.rules) {
        lines.push('', `### ${rule.title}`);
        if (rule.body.trim()) lines.push(rule.body.trim());
      }
    }

    return `${lines.join('\n').trim()}\n`;
  }
}
